SET SERVEROUTPUT ON SIZE UNLIMITED


PROMPT === INSERTAR USUARIO ===

DECLARE
  V_ID  NUMBER;
  V_RET NUMBER;
  V_MSG VARCHAR2(4000);
BEGIN
  PKG_MUE_USUARIO.PR_USUARIO_INSERTAR(
    P_ROL_ROL              => 1,
    P_TDC_TIPO_DOCUMENTO   => 1,
    P_PRF_PROFESION        => NULL,
    P_USU_LOGIN            => 'usuario_test',
    P_USU_PASSWORD_HASH    => 'HASH123',
    P_USU_ACTIVO           => 1,
    P_USU_NUMERO_DOCUMENTO => 123456789,
    P_USU_PRIMER_NOMBRE    => 'Juan',
    P_USU_SEGUNDO_NOMBRE   => 'Carlos',
    P_USU_PRIMER_APELLIDO  => 'Perez',
    P_USU_SEGUNDO_APELLIDO => 'Lopez',
    P_USU_FECHA_DE_NACIMIENTO => SYSDATE,
    P_USU_TELEFONO_RESIDENCIA => 12345678,
    P_USU_TELEFONO_CELULAR    => 87654321,
    P_USU_ZONA            => 1,
    P_USU_MUNICIPIO       => 'Guatemala',
    P_USU_DEPARTAMENTO    => 'Guatemala',
    P_USU_CIUDAD          => 'Guatemala',
    P_USU_CORREO          => 'test@mail.com',
    P_USU_NIT             => 1234567,
    O_USU_USUARIO        => V_ID,
    O_COD_RET            => V_RET,
    O_MSG                => V_MSG
  );

  DBMS_OUTPUT.PUT_LINE('INSERT RET=' || V_RET || ' MSG=' || V_MSG || ' ID=' || V_ID);
END;
/

PROMPT === OBTENER USUARIO ===

DECLARE
  V_RET NUMBER;
  V_MSG VARCHAR2(4000);
BEGIN
  PKG_MUE_USUARIO.PR_USUARIO_OBTENER(
    P_USU_USUARIO => 1,
    O_CURSOR      => :CUR,
    O_COD_RET     => V_RET,
    O_MSG         => V_MSG
  );

  DBMS_OUTPUT.PUT_LINE('OBTENER RET=' || V_RET || ' MSG=' || V_MSG);
END;
/

PROMPT === LISTAR USUARIOS ===

DECLARE
  V_CUR SYS_REFCURSOR;
  V_RET NUMBER;
  V_MSG VARCHAR2(4000);

  V_ID NUMBER;
  V_LOGIN VARCHAR2(50);
BEGIN
  PKG_MUE_USUARIO.PR_USUARIO_LISTAR(
    O_CURSOR  => V_CUR,
    O_COD_RET => V_RET,
    O_MSG     => V_MSG
  );

  DBMS_OUTPUT.PUT_LINE('LISTAR RET=' || V_RET || ' MSG=' || V_MSG);

  LOOP
    FETCH V_CUR INTO V_ID, V_LOGIN;
    EXIT WHEN V_CUR%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('ID=' || V_ID || ' LOGIN=' || V_LOGIN);
  END LOOP;

  CLOSE V_CUR;
END;
/

PROMPT === ACTUALIZAR USUARIO ===

DECLARE
  V_RET NUMBER;
  V_MSG VARCHAR2(4000);
BEGIN
  PKG_MUE_USUARIO.PR_USUARIO_ACTUALIZAR(
    P_USU_USUARIO         => 1,
    P_ROL_ROL             => 1,
    P_TDC_TIPO_DOCUMENTO  => 1,
    P_PRF_PROFESION       => NULL,
    P_USU_LOGIN           => 'usuario_test_mod',
    P_USU_NUMERO_DOCUMENTO => 123456789,
    P_USU_PRIMER_NOMBRE   => 'Juan Mod',
    P_USU_SEGUNDO_NOMBRE  => 'Carlos',
    P_USU_PRIMER_APELLIDO => 'Perez',
    P_USU_SEGUNDO_APELLIDO=> 'Lopez',
    P_USU_FECHA_DE_NACIMIENTO => SYSDATE,
    P_USU_TELEFONO_RESIDENCIA => 11111111,
    P_USU_TELEFONO_CELULAR    => 22222222,
    P_USU_ZONA           => 2,
    P_USU_MUNICIPIO      => 'Mixco',
    P_USU_DEPARTAMENTO   => 'Guatemala',
    P_USU_CIUDAD         => 'Mixco',
    P_USU_CORREO         => 'mod@mail.com',
    P_USU_NIT            => 7654321,
    O_COD_RET            => V_RET,
    O_MSG                => V_MSG
  );

  DBMS_OUTPUT.PUT_LINE('UPDATE RET=' || V_RET || ' MSG=' || V_MSG);
END;
/

PROMPT === CAMBIAR ESTADO ===

DECLARE
  V_RET NUMBER;
  V_MSG VARCHAR2(4000);
BEGIN
  PKG_MUE_USUARIO.PR_USUARIO_CAMBIAR_ESTADO(
    P_USU_USUARIO => 1,
    P_USU_ACTIVO  => 0,
    O_COD_RET     => V_RET,
    O_MSG         => V_MSG
  );

  DBMS_OUTPUT.PUT_LINE('ESTADO RET=' || V_RET || ' MSG=' || V_MSG);
END;
/

PROMPT === LOGIN USUARIO ===

DECLARE
  V_RET NUMBER;
  V_MSG VARCHAR2(4000);
BEGIN
  PKG_MUE_USUARIO.PR_USUARIO_LOGIN(
    P_USU_LOGIN    => 'usuario_test',
    P_USU_PASSWORD => 'HASH123',
    O_CURSOR       => :CUR,
    O_COD_RET      => V_RET,
    O_MSG          => V_MSG
  );

  DBMS_OUTPUT.PUT_LINE('LOGIN RET=' || V_RET || ' MSG=' || V_MSG);
END;
/

PROMPT === ELIMINAR USUARIO ===

DECLARE
  V_RET NUMBER;
  V_MSG VARCHAR2(4000);
BEGIN
  PKG_MUE_USUARIO.PR_USUARIO_ELIMINAR(
    P_USU_USUARIO => 1,
    O_COD_RET     => V_RET,
    O_MSG         => V_MSG
  );

  DBMS_OUTPUT.PUT_LINE('DELETE RET=' || V_RET || ' MSG=' || V_MSG);
END;
/

PROMPT === VERIFICACIÓN FINAL ===

SELECT COUNT(*) AS TOTAL
FROM MUE_USUARIO
WHERE USU_Login LIKE 'usuario_test%';